""" This can help when snapping,
    so as to use the raw mesh
    instead of the one generated by the modifier
"""

import bpy

enable_bevel = True

for obj in bpy.context.selected_objects:
    if len(obj.modifiers) > 0:
        for mod in obj.modifiers:
            if mod.type == 'BEVEL':
                if mod.show_viewport != enable_bevel:
                    mod.show_viewport = enable_bevel
